name: artifact-practice
on: [push, pull request]

jobs:
  upload-job:
    name: Save output
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: expr 1+1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: output-log-file
          path: output.log
  download-job:
    runs-on: ubuntu-latest
    needs: upload-job
    steps:
      - name: Dounload a single artifact
        uses: actions/download-artifact@v4
        with:
          name: output-log-file
      - run: cat output.log